apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: voice-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: abhishekanbu01/frontend2:latest  # Updated to match your docker run command
        ports:
        - containerPort: 3000 # Updated to match your actual container port
        env:
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: voice-ai-config
              key: BACKEND_URL
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: voice-ai-secrets
              key: API_KEY
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: voice-ai
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
